fix main readme images background
eclipse-uprotocol/uprotocol-spec pull request #2
Opened 2023-06-06 00:22 UTC by yrtimiD

Added white rectangle behind the image to ensure always readable text + some visual padding around. Additionally, this ensures that after future editing of the diagrams on the draw.io bg customizations are not lost.

2023-06-08 00:20 UTC, stevenhartley requested changes
Please see comments.

2023-06-08 00:20 UTC, stevenhartley commented on layers.drawio.svg
Some of the icons have disappeared when I look at the diff (AMQP, DDS, CloudEvent, etc))

2023-06-08 00:20 UTC, stevenhartley commented on overview.drawio.svg
Same comment as previous, cloudevent icon is missing.

2023-06-08 00:20 UTC, stevenhartley commented on ues.drawio.svg
Font has changed, I would prefer to keep the old font

2023-06-08 09:35 UTC, yrtimiD commented on overview.drawio.svg
Fixed this. These two images were not originally embedded but fetched from the remote location making them disappear randomly. Now they are embedded and should not make surprises.

2023-06-08 09:42 UTC, yrtimiD commented on ues.drawio.svg
thanks, embedded the font, now should work always
(and changed font style for the "Legend" label to be as all other, hope this is ok?)

2023-06-08 09:45 UTC, yrtimiD commented on layers.drawio.svg
Fixed this. These two images were not originally embedded but fetched from the remote location making them disappear randomly. Now they are embedded and should not make surprises.

2023-06-08 09:47 UTC, yrtimiD commented on overview.drawio.svg
fixed

2023-06-16 11:57 UTC, stevenhartley approved these changes
Thank you for the change!

2023-06-16 11:57 UTC, merged